version: "3.9"

services:
  backend:
    build: ./backend
    container_name: video-summary-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/audio:/app/audio
      - ./backend/outputs:/app/outputs
    restart: unless-stopped

  frontend:
    build: ./frontend  # Path to your frontend folder
    container_name: lazy-watch-frontend
    ports:
      - "3000:80"      # Map your computer's 3000 to Container's 80
    restart: unless-stopped
    depends_on:
      - backend